// <auto-generated />
using System;
using FFRaidAnalytics.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FFRaidAnalytics.Migrations
{
    [DbContext(typeof(FFRaidAnalyticsContext))]
    partial class FFRaidAnalyticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("FFRaidAnalytics.Models.EncounterModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncounterName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("FFRaidAnalytics.Models.FFLogsTokenModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresIn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RateLimitResetsAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TokenObtainedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("FFRaidAnalytics.Models.PlayerModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Server")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Server")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FFRaidAnalytics.Models.ReportFightModel", b =>
                {
                    b.Property<string>("ReportCode")
                        .HasColumnType("TEXT");

                    b.Property<long>("FightNo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EncounterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("FightPercentage")
                        .HasColumnType("REAL");

                    b.Property<bool>("Kill")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ReportCode", "FightNo");

                    b.ToTable("ReportFights");
                });

            modelBuilder.Entity("FFRaidAnalytics.Models.ReportFightPlayerModel", b =>
                {
                    b.Property<string>("ReportCode")
                        .HasColumnType("TEXT");

                    b.Property<long>("FightNo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<long>("DamageDone")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HealingDone")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReportCode", "FightNo", "PlayerId");

                    b.ToTable("ReportFightPlayers");
                });

            modelBuilder.Entity("FFRaidAnalytics.Models.ReportModel", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
